apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: default
spec:
  clusterIP: 10.233.7.157
  clusterIPs:
    - 10.233.7.157
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
    managedBy: terraform
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
