kind: ConfigMap
apiVersion: v1
metadata:
  name: home-assistant-configmap
  namespace: home-assistant
data:
  known_devices.yaml: |
  automations.yaml: |
  configuration.yaml: |-
    default_config:
    frontend:
      themes: !include_dir_merge_named themes
    automation: !include automations.yaml
    http:
      server_port: 80
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/16
        - 127.0.0.1
        - 192.168.0.0/24
        - 192.168.0.240
        - 10.233.0.0/18