kind: ConfigMap
apiVersion: v1
metadata:
  name: home-assistant-configmap
  namespace: home-assistant
data:
  known_devices.yaml: |
  automations.yaml: |
  configuration.yaml: |-
    default_config:
    frontend:
      themes: !include_dir_merge_named themes
    automation: !include automations.yaml
    http:
      server_port: 80
      use_x_forwarded_for: true
      trusted_proxies:
        - 192.168.0.249
        - 192.168.0.157
        - 192.168.0.115
        - 192.168.0.100
        - 192.168.0.22
        - 192.168.0.46
        - 127.0.0.1