---
apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant
---
apiVersion: v1
kind: Service
metadata:
  namespace: home-assistant
  name: home-assistant
spec:
  selector:
    app: home-assistant
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: home-assistant
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: homeassistant/home-assistant:2024.10.2
          #        resources:
          #          requests:
          #            memory: "1Gi"
          #          limits:
          #            memory: "1.5Gi"
          ports:
            - containerPort: 8123
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /config/configuration.yaml
              subPath: configuration.yaml
              name:  home-assistant-configmap
            - mountPath: /config/automations.yaml
              subPath: automations.yaml
              name:  home-assistant-configmap
          # - mountPath: /dev/ttyUSB1
          #   name: zigbee
          securityContext:
            privileged: true
            # capabilities:
            #   add:
            #     - NET_ADMIN
            #     - NET_RAW
            #     - SYS_ADMIN
      hostNetwork: true
      # nodeSelector:
      #   workload: india
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: home-assistant-pvc
        - name:  home-assistant-configmap
          configMap:
            name: home-assistant-configmap
      # - name: zigbee
      #   hostPath:
      #     path: /dev/ttyACM0
---
apiVersion: v1
kind: Service
metadata:
  namespace: home-assistant
  name: zwavejs2mqtt
spec:
  selector:
    app: zwavejs2mqtt
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8091
      targetPort: 8091
    - name: ws
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: home-assistant
  name: zwavejs2mqtt-india
  labels:
    app: zwavejs2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zwavejs2mqtt
  template:
    metadata:
      labels:
        app: zwavejs2mqtt
    spec:
      # restartPolicy: OnFailure
      containers:
        - name: zwavejs2mqtt
          image: zwavejs/zwavejs2mqtt:9.23.0
          ports:
            - containerPort: 8091
            - containerPort: 3000
          volumeMounts:
            - mountPath: /usr/src/app/store
              name: configuration
          # - mountPath: /dev/ttyACM0
          #   name: zwave
          securityContext:
            privileged: true
      volumes:
        - name: configuration
          persistentVolumeClaim:
            claimName: zwavejs2mqtt-india-pvc
      # - name: zwave
      #   hostPath:
      #     path: /dev/ttyACM0
      # nodeSelector:
      #   workload: india
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: arm64v8/eclipse-mosquitto
          securityContext:
            privileged: true
          ports:
            - containerPort: 1883
            - containerPort: 9001
      nodeSelector:
        workload: india
---
apiVersion: v1
kind: Service
metadata:
  namespace: home-assistant
  name: mosquitto-service
spec:
  selector:
    app: mosquitto-service
  type: ClusterIP
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: mqtt1
      protocol: TCP
      port: 9001
      targetPort: 9001

