
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: home-assistant
data:
  mosquitto.conf: |

    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout
    
    # MQTTS listener
    listener 8883
    protocol mqtt

    cafile /etc/ssl/certs/ca-certificates.crt
    keyfile /mosquitto/certs/tls.key
    certfile /mosquitto/certs/tls.crt

    # WS Listener
    listener 9001
    protocol websockets

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
  name: mosquitto-data
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto
          ports:
            - containerPort: 8883
            - containerPort: 9001
          volumeMounts:
            - mountPath: /etc/mosquitto/
              name: config
   ##         - mountPath: /mosquitto/certs/
    ##          name: certs
            - mountPath: /mosquitto/data/
              name: data
      volumes:
        - name: config
          configMap:
            name: mosquitto-config
  ##      - name: certs
  ##        secret:
  ##          secretName: mosquitto-certs
        - name: data
          persistentVolumeClaim:
            claimName: mosquitto-data



---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-mqtts
  namespace: home-assistant
spec:
  type: NodePort
  selector:
    app: mosquitto
  ports:
    - port: 8883
      nodePort: 30883
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-ws
  namespace: home-assistant
spec:
  type: ClusterIP
  selector:
    app: mosquitto
  ports:
    - port: 9001