apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: web-colettifam-com
  namespace: default
spec:
  secretName: web-colettifam-com-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - colettifam-com
#  privateKey:
#    algorithm: RSA
#    encoding: PKCS1
#    size: 2048
  dnsNames:
    - web.colettifam.com
  issuerRef:
    name: letsencrypt-stage
    kind: ClusterIssuer
    group: cert-manager.io